/* Fixed examples generated by the Python engine; no user text is collected. */
(() => {
  const examples = window.BOWDEN_EXAMPLES;
  const original = document.querySelector("#original-text");
  if (!original || !examples) return;

  const redacted = document.querySelector("#redacted-text");
  const policy = document.querySelector("#policy");
  const buttons = [...document.querySelectorAll("[data-example]")];
  const german = document.documentElement.lang === "de";
  const descriptions = german
    ? {
        strict:
          "Strikt umfasst alle unterstützten deterministischen Kennungsklassen, einschliesslich URLs.",
        balanced:
          "Ausgewogen behält URLs bei. Kontakt-, Netzwerk- und unterstützte Finanzkennungen werden weiterhin maskiert.",
        permissive:
          "Zurückhaltend behält URLs, IP- und MAC-Adressen sowie eigenständige UID-Werte bei. AHV-, Bank-, Karten- und MWST-Kennungen sowie E-Mail-Adressen und Telefonnummern werden weiterhin maskiert.",
      }
    : {
        strict:
          "Strict includes all supported deterministic identifier classes, including URLs.",
        balanced:
          "Balanced keeps URLs. It still redacts contact, network, and supported financial identifiers.",
        permissive:
          "Permissive keeps URLs, IP and MAC addresses, and standalone UID values. AHV, bank, card, VAT, email, and phone identifiers remain in scope.",
      };
  let selected = "account";

  function renderOriginal(text, spans) {
    original.replaceChildren();
    let cursor = 0;
    for (const span of spans) {
      original.append(document.createTextNode(text.slice(cursor, span.start)));
      const mark = document.createElement("mark");
      mark.textContent = text.slice(span.start, span.end);
      mark.title = span.label;
      original.append(mark);
      cursor = span.end;
    }
    original.append(document.createTextNode(text.slice(cursor)));
  }

  function renderRedacted(text) {
    redacted.replaceChildren();
    for (const part of text.split(/(\[[A-Z_]+_\d+\])/g)) {
      if (/^\[[A-Z_]+_\d+\]$/.test(part)) {
        const mark = document.createElement("mark");
        mark.textContent = part;
        redacted.append(mark);
      } else {
        redacted.append(document.createTextNode(part));
      }
    }
  }

  function render() {
    const example = examples[selected];
    const result = example.policies[policy.value];
    renderOriginal(example.text, result.spans);
    renderRedacted(result.redacted);
    const unique = new Set(result.spans.map((span) => span.replacement)).size;
    document.querySelector("#example-summary").textContent = german
      ? `${result.spans.length} Textstellen maskiert · ${unique} eindeutige Platzhalter`
      : `${result.spans.length} spans redacted · ${unique} unique placeholders`;
    document.querySelector("#policy-description").textContent =
      descriptions[policy.value];
    for (const button of buttons) {
      const active = button.dataset.example === selected;
      button.setAttribute("aria-pressed", String(active));
      button.classList.toggle("active", active);
    }
  }

  for (const button of buttons) {
    button.addEventListener("click", () => {
      selected = button.dataset.example;
      render();
    });
  }
  policy.addEventListener("change", render);
  render();
})();
